stages:
  - build

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Running code review with pr-review-agent"
    - echo "GITLAB_TOKEN $GITLAB_TOKEN"
    - echo "GIT_REPOSITORY $GIT_REPOSITORY"
    - echo "GOOGLE_CLOUD_PROJECT $GOOGLE_CLOUD_PROJECT"
    - echo "GOOGLE_CLOUD_LOCATION $GOOGLE_CLOUD_LOCATION"
    - echo "GOOGLE_CLOUD_CREDENTIALS_JSON $GOOGLE_CLOUD_CREDENTIALS_JSON"
    - echo "GIT_PR_NUMBER $GIT_PR_NUMBER"
    - echo "GITLAB_API_URL $GITLAB_API_URL"
    - >
      docker run --rm -v $CI_PROJECT_DIR:/workspace
      -e GITLAB_TOKEN="$CI_JOB_TOKEN"
      -e GIT_REPOSITORY="$CI_PROJECT_PATH"
      -e GOOGLE_CLOUD_PROJECT="$GOOGLE_CLOUD_PROJECT"
      -e GOOGLE_CLOUD_LOCATION="$GOOGLE_CLOUD_LOCATION"
      -e GOOGLE_CLOUD_CREDENTIALS_JSON="$GOOGLE_CLOUD_CREDENTIALS_JSON"
      -e GIT_PR_NUMBER="$CI_MERGE_REQUEST_IID"
      -e GITLAB_API_URL="$CI_API_V4_URL"
      europe-west2-docker.pkg.dev/iamreleased/docker-images/pr-review-agent-gitlab:latest
  only:
    - branches
